reviews:
  profile: "chill"
  instructions: |
    - Focus on severe logic errors, security issues, and bugs.
    - Ignore minor nitpicks, UI styling choices, and formatting issues.
    - Do not complain about unused variables if they are a work-in-progress.
  auto_review:
    enabled: true
    base_branches:
      - 'main'
      - 'coordly-chadi-omar'
      - 'gym-sharifa-mhmdharkous-khaled'
      - 'pharmacy-ali-mazen-mirna'
      - 'pathway-sarah-alaa'
      - 'margin-nancy-jeanpaul-yorgo/main'
      - 'bashaar-bahaa'
      - 'hadisaiibi-mouhannad'
      - 'hoda-jad-jeanluc'
      - 'hadimatar-mhmdfarchoukh'
      - 'mhmdfarhat-mhmdali-amir'
