reviews:
  auto_review:
    enabled: true
    base_branches:
      - 'main'
      - 'coordly-chadi-omar'
      - 'gym-sharifa-mhmdharkous-khaled'
      - 'pharmacy-ali-mazen-mirna'
      - 'pathway-sarah-alaa'
      - 'margin-nancy-jeanpaul-yorgo/main'
      - 'bashaar-bahaa'
      - 'hadisaiibi-mouhannad'
      - 'hoda-jad-jeanluc'
      - 'hadimatar-mhmdfarchoukh'
      - 'mhmdfarhat-mhmdali-amir'
